baseURL = "http://901runner.com"
enableEmoji = true
googleAnalytics = "UA-111788534-2"
languageCode = "en-us"
theme = "minimal"
title = "901 Runner"
[[menu.icon]]
name = "strava"
url = "https://www.strava.com/athletes/denniswebb"
weight = 3
[[menu.icon]]
name = "instagram"
url = "https://www.instagram.com/901runner/"
weight = 2
[[menu.icon]]
name = "envelope-o"
url = "mailto:dhwebb@gmail.com"
weight = 1
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 3
[[menu.main]]
name = "Training Log"
url = "/log/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "green"
author = "Dennis Webb"
backgroundColor = "white"
font = "Rubik"
githubUsername = "denniswebb"
showBorder = true
